### ISSUE TITLE
feature request : require token on each call

### ISSUE THREAD

**Issue by jmls** [chiefy/vaulted#54]
When I use a token that is "powerful" (like a root token, for example) I would like to be able to remove the token from memory. 

The reason for this is that I could use the root token to perform a task, and for another another task "forget" to set another less privileged token, so the _current_ token (root) is used. This may not be intentional, but it could provide for security breaches.

I would prefer for the token to be passed into every call, so that there _has_ to be a vaild and authenticated token for each read/write to vault

At the moment, I am calling setToken(uuid.v4()) as a workaround, and it seems to fit my use-case, but requires that I remember to "reset" the token after _every_ call which is error-prone and not secure.

**Comment by kenjones-cisco** [comment]
The approach I've taken with this is to include a configuration option `no_global_token` which defaults to `false`. Such that if you set it to `true`, then calls to `setToken` will not actually set the token or the token header globally. A check is added to see if an API option included `token`, if so then set the `headers` option appropriately. Then check if the `headers` was set properly, if not throw an Error indicating that a token was required.

This provides continued support to leverage existing approach, but through the use of a single configuration disable that and then require a token to be provided as part of the options for each API.

I need to do some testing then update some of the APIs to accept options as input that currently do not so that token can be provided.
